baseURL = "https://dcm.samorso.ch/"
languageCode = "en-US"
defaultContentLanguage = "en"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"

title = "Data and Code Management: From Collection to Application"
# theme = "hugo-theme-relearn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

googleAnalytics = "UA-176152424-1" # add Google Analytics
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
ignoreLogs = ['warning-goldmark-raw-html']

[module]
  [[module.imports]]
    path = "github.com/McShelby/hugo-theme-relearn"
    # optional: pin to a tag you like
    # version = "v6.0.0"

[params]
  author.name = "Samuel Orso"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disable.search = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = ["auto", "relearn-light", "relearn-dark"]
  # Eneabling Emoji
  enableEmoji=true
  disableSearchHiddenPages = true
  disableSeoHiddenPages = true
  disableTagHiddenPages = true

[outputs]
home = [ "HTML", "RSS"]

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/DaCM2025/"
weight = 5

[[menu.shortcuts]]
name = "<i class='fa fa-fw fa-users'></i> Discussion forum"
identifier = "fm"
url = ""
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-fw fa-book'></i> Lectures"
identifie = "book"
url = "https://smac-group.github.io/ds/"
weight = 15
